# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      # Future
      # - name: Test
      #   run: npm run test
